### ISSUE TITLE
Support $search query parameter

### ISSUE THREAD

**Issue by MatthiasWeibel** [techniq/odata-query#11]
Hi,

As far as I can see the $search query parameter is not supported. Do you plan to implement that?
http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part2-url-conventions/odata-v4.0-errata03-os-part2-url-conventions-complete.html#_Toc453752364

Thanks!

**Comment by techniq** [comment]
I think last time I looked the ASP.NET WebApi implementation didn't have support for `$search` so I never used it and thus wasn't sure how best to support it.   It shouldn't be too difficult to add support though.  A few questions:

- Are you using a backend that does support `$search`, and if so, which one?
- Could the API be as simple as `{ search: 'your expression' }` where you pass any expression as a string, or do you think we should add operators, etc?

**Comment by MatthiasWeibel** [comment]
I am using odata-query for querying Microsoft Graph. 
https://developer.microsoft.com/en-us/graph/docs/concepts/query_parameters#search-parameter

And for that the API could be as simple as `{ search: 'your expression' }`.

**Comment by techniq** [comment]
I just released `5.1.0` with this added.  Give it a try and let me know.

**Comment by MatthiasWeibel** [comment]
Wow! That was quick. I will let you know!

Thanks!

**Comment by MatthiasWeibel** [comment]
Looks good!
Thanks!
