### ISSUE TITLE
[Question] Is the project maintained? 

### ISSUE THREAD

**Issue by sitek94** [techniq/odata-query#112]
Hey there!

Is the package maintained? I'm asking, because we're thinking about introducing it in our project and we're wondering if you're open for possible contributions or should we just create our own fork?

Btw the package itself is great, API is very intuitive, great job!

Cheers

**Comment by techniq** [comment]
Hey @sitek94, thanks for the nice words.  I no longer use OData on active projects (switched to GraphQL / SvelteKit data loaders a few years ago). 

With that said, I could add you as a collaborator and would push NPM releases as you needed, if you would rather not manage your own fork.

**Comment by techniq** [comment]
Done.  Thanks for helping out.  I'll try to cut a release whenever I see a PR merged (hopefully I can stay on top of them).  If you'd want to setup a workflow to publish to NPM via a Github action, I'd be open to that as well.

**Comment by sitek94** [comment]
Definitely! When I have a minute I'll prepare a workflow for that, so it's less of a burden for you, cheers!
