### ISSUE TITLE
Example Project - Source Code

### ISSUE THREAD

**Issue by ahbtoplama** [techniq/odata-query#17]
Hi
Can you share odata-query sample express project for newbies ?

**Comment by techniq** [comment]
@ahbtoplama `odata-query` is only used to generate queries (typically on the frontend).

For the backend, I typically use [ASP.NET](https://github.com/OData/WebApi) (see also: https://odata.github.io/).

Here are some example services you can use to test things out:
- http://services.odata.org/V4/Northwind/
- http://services.odata.org/V4/TripPinService/

You could also use something like [JayStack](https://jaystack.com/products/jaystack-odata-v4-server/) for a node backend, but I do not have any experience with it.  Some people have also used it to query [Microsoft Graph](https://developer.microsoft.com/en-us/graph) which supports OData.

Lastly, if you use React on the frontend, you might be interested in using my [react-odata](https://github.com/techniq/react-odata) component.
