### ISSUE TITLE
How to use it with Type script ts file

### ISSUE THREAD

**Issue by DinkuMM** [techniq/odata-query#2]
Hi i need to access this js library from a ts file in angular2.

**Comment by techniq** [comment]
I don't use Typescript, but from my understanding it wouldn't be any different than regular Javascript/Ecmascript using ES6/7 syntax with babel.

```js
import buildQuery from 'odata-query'

const query = buildQuery({...})
fetch(`http://localhost${query}`)
```

Are you receiving a specific error?  I'm currently using it within a React app with Webpack/Babel.

**Comment by DinkuMM** [comment]
Thanks its working. it was my mistake

**Comment by andreyciocan** [comment]
@DinkuMM how did you fixed? For me it asks to import @types/odata-query. But this does not exist
