### ISSUE TITLE
IN operator

### ISSUE THREAD

**Issue by techniq** [techniq/odata-query#22]
[Currently](https://github.com/techniq/odata-query/blob/master/src/index.js#L190-L204) we explode an `in` operator into multiple `eq`/`or`.  For [example](https://github.com/techniq/odata-query/blob/master/src/index.test.js#L42):
```js
const filter = { SomeProp: { in: [1, 2, 3] } };
const actual = buildQuery({ filter });
=> '?$filter=(SomeProp eq 1 or SomeProp eq 2 or SomeProp eq 3)'
```

When attempting to do this with a lot of values, I received a `414 (URI Too Long)` error.  Upon more researching, I found this proposal to support an actual `in` operator, and it appears to be accepted.: https://issues.oasis-open.org/browse/ODATA-556

I then tested against my WebApi/OData backend and it appears to work when using `$filter=Id in (1,2,3,4,5)` or `$filter=Code in ('abc','def','ghi')`

While not in the `4.0` [spec](http://docs.oasis-open.org/odata/odata/v4.0/errata03/os/complete/part1-protocol/odata-v4.0-errata03-os-part1-protocol-complete.html#_Toc453752288), I just found mention of it in the `4.01` spec [part1](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part1-protocol/odata-v4.01-cs01-part1-protocol.html#sec_BuiltinFilterOperations) and [part 2](http://docs.oasis-open.org/odata/odata/v4.01/cs01/part2-url-conventions/odata-v4.01-cs01-part2-url-conventions.html#sec_In).

Considering supporting this and releasing as a breaking change (`6.0.0`)

**Comment by techniq** [comment]
This commit seems to supply `IN` support, but surprisingly I'm still on `7.0.0` and it looks like this wasn't implemented till `7.0.1` - https://github.com/OData/WebApi/commit/116e20d8ecd53a2d6e3a933ff924c0c63d12d631

**Comment by ulfdahlstrand** [comment]
Hi, the issue seam to be resolved. is it possible to make a new version of this. currently i have built a wrapper to the lib but it would be awesome if the lib could be updated :)

**Comment by Jakob-Koschel** [comment]
@ulfdahlstrand are you able to share your code for the wrapper. I have the same issue right now and it would safe me some time if you could share your wrapper :) Thx!
