### ISSUE TITLE
Support empty `any()` operator

### ISSUE THREAD

**Issue by techniq** [techniq/odata-query#23]
[Spec](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html#_Toc371341806)
> The any operator without an argument returns true if the collection is not empty.

This would be a breaking change from how we [currently](https://github.com/techniq/odata-query/blob/master/src/index.js#L186-L188) handle this

**Comment by techniq** [comment]
One workaround is to do something like

```js
SomeCollection: {
  any: { Id: { gt: 0 } }
}
```

**Comment by Sayan751** [comment]
@techniq Any tentative plan to support this?

**Comment by techniq** [comment]
@Sayan751 no plans myself. I'm not actively developing this project anymore (just maintaining) as none of my current projects use OData (I've been using GraphQL).

**Comment by Sayan751** [comment]
@techniq That's a pity 😢 In that case, I will try to work on this issue in my free time. 

On a different note, during my last PR, I noticed that the build script for this package, as well as the babel dependencies are quite old (actually the build script does not work on my windows machine). Do you mind if I update that as well?

**Comment by techniq** [comment]
@Sayan751 I saw that in your last PR and rolled it back. That would be great if you could update those.

I've recently starting using [tsdx](https://github.com/palmerhq/tsdx) for my non-app projects (else I use create react app / gatsby / etc).  Not sure you would want to bring Typescript into the project, but if you would, tsdx might be a good solution to manage the build/etc.
