### ISSUE TITLE
Import issues

### ISSUE THREAD

**Issue by adishupadhyay** [techniq/odata-query#24]
Hi Team , 
I have installed this library as per instruction, But  when i am using it, its giving issue odataQuery  is not defined.
Below are my code for test. I tested it on 6.9 and 8.0 both.
var odataQuery = require("odata-query")
const filter = [{ SomeProp: 1 }, { AnotherProp: 2 }, 'startswith(Name, "foo")'];
oDataQuery({ filter })
console.log('oDataQuery..'+oDataQuery);.

Thanks ,

**Comment by techniq** [comment]
Are you using node?  I've only verified support with webpack.

**Comment by techniq** [comment]
There shouldn't be Anything keeping it from working on node but you'll need
to tranpile it to target it (es6 features, etc). Also depends on the
version of node and ecmascipt supported features.

I'm out of town so not going to be much more help for a bit.

**Comment by samuelportz** [comment]
Try 
```javascript
const odataQuery = require("odata-query").default;
const filter = [{ SomeProp: 1 }, { AnotherProp: 2 }, 'startswith(Name, "foo")'];
oDataQuery({ filter })
console.log('oDataQuery..'+oDataQuery);
```

For server side node you need `require("odata-query").default`
