### ISSUE TITLE
Odata in and and

### ISSUE THREAD

**Issue by svemoory** [techniq/odata-query#3]
Hi I am trying to implement 'and' and 'in' in conjunction and it's not working because of the placement of () around the 'in'. 

    filter= { 
          and: [
              {prop1: `${prop1}`}, { prop2:`${prop2}`},  ({prop3: {'in': ['value1','value2'] }})]              
          };
The issue is it is doing 
$filter=(prop1 eq prop1 and prop2 eq prop2 or prop3 eq value1 or prop3 eq value2)

what I want
$filter=(prop1 eq prop1 and prop2 eq prop2 and (prop3 eq value1 or prop3 eq value2 or...)

Where am I going wrong?

**Comment by techniq** [comment]
You use arrays `[]` to control the parens, so if you wrap the third parameter `prop3` in brackets, it will give you the desired output.

```js
const filter = {
  and: [
    { prop1: `${prop1}` },
    { prop2: `${prop2}` },
    [{ prop3: { in: ['value1', 'value2'] } }],
  ],
};

buildQuery({filter})
// => "?$filter=(prop1 eq 'prop1' and prop2 eq 'prop2' and (prop3 eq 'value1' or prop3 eq 'value2'))"
```

[CodeSandbox](https://codesandbox.io/s/gJXJ7OkxZ) if you want to play around with the syntax.

**Comment by svemoory** [comment]
Thanks. That worked.
