### ISSUE TITLE
Comparing two columns

### ISSUE THREAD

**Issue by relair** [techniq/odata-query#32]
There doesn't seem to be an easy way of comparing two columns using this library, with raw odata we can do simple
`?$filter=SomeProp eq AnotherProp`
but if we do
`const filter = { SomeProp: 'AnotherProp' };`
then we would get 
`?$filter=SomeProp eq 'AnotherProp'`
which would do string comparison with string 'AnotherProp' and not the column of that name.

I was thinking if there is no better way if we could expand data types with type 'column' to achieve this
`const filter = { "someProp": { eq: { type: 'column', value: 'AnotherProp' } } };`
Is there maybe a better way to do it, that I have missed?

**Comment by techniq** [comment]
While maybe not very intuitive, you should be able to use `type: 'raw'` to accomplish this...
```js
const filter = { someProp: { eq: { type: 'raw', value: 'AnotherProp' } } };
const expected = '?$filter=someProp eq AnotherProp';
```
- https://github.com/techniq/odata-query/blob/master/src/index.test.js#L659-L664

**Comment by relair** [comment]
Thank you for a good suggestion, I will try it. Probably would be worth adding an example to readme at some point. Feel free to close this if you wish.
