### ISSUE TITLE
Date type not reading UTC format

### ISSUE THREAD

**Issue by solidflows** [techniq/odata-query#4]
When converting from ISO String to Date object, the library leaves off the milliseconds before the timezone string.

Ex.
Convert **2017-06-05T00:00:00.000Z** to date object and pass to filter.
Filter creates URL string with **2017-06-05T00:00:00Z**
The URL string should be **2017-06-05T00:00:00.000Z**

Inside the filter object, I'm passing this date object:
**Sun Jun 04 2017 20:00:00 GMT-0400 (EDT)**

Let me know if you need me to provide anything else

**Comment by techniq** [comment]
@solidflows I just published v3.3.2 that resolves this issue.  For some reason I was explicitly stripping off the milliseconds but I couldn't find the reason why.  Give the latest version a try and let me know if you find any other problems.  Thanks.

**Comment by solidflows** [comment]
Thanks for the quick turn-around! Just tried it and now works. Thanks again!
