### ISSUE TITLE
Can v6 be considered stable?

### ISSUE THREAD

**Issue by zhaparoff** [techniq/odata-query#47]
Hello,

First of all, thanks for the great tool!

Have a question - can v6 be considered stable?
I'm going to use it in the TypeScript project, so I need type definitions, which are missing in the latest one, which is `5.7.0`.

**Comment by Sayan751** [comment]
@zhaparoff The work is not yet completed. I got busy with other stuff. I would love to come back to this at some point in future and finish the work. Till then here is a bare minimal type definition you can use.

```typescript
declare module "odata-query" {
    export default function buildQuery(parameters: any): string;
}
```

**Comment by zhaparoff** [comment]
@Sayan751 
Thanks for quick feedback. 
Can I use type definitions from v6 with 5.7.0 instead? Are they compatible? Or there were some API changes that are not supported by v5.x?

**Comment by Sayan751** [comment]
The target is to make those compatible. At this point the typings in v6 is pretty complicated, and can should be made simpler.
AFAIK, there is support for collection operator in v6, refer https://github.com/techniq/odata-query/issues/23. Apart from that there should no be any breaking change in API in v6. The method signature changes are all internal. From that perspective, the API is compatible, altough the typing may not.
Having said that feel free to give v6 a try. Would love to hear feedback from you.
