### ISSUE TITLE
Filter functions contain space causing Odata error

### ISSUE THREAD

**Issue by solidflows** [techniq/odata-query#5]
When passing filter functions such as `contains`, `startswith`, `endswith`, etc. there's a space being added between column name and value.

With updates to Odata it might have a stricter check to avoid spacing inside the function.

startswith(Name, "foo") should be
startswith(Name,"foo")  <<<<<<< No space inside

**Comment by techniq** [comment]
It should be `startswith(Name,'foo')` and not `startswith(Name,"foo")` correct?

I looked at the [spec](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part2-url-conventions.html) and it does not include the space so I removed it, although I haven't ran into an issue with my Odata backends using [WebApi](https://github.com/OData/WebApi).  Have you ran into an issue with this yourself?

---

Btw, I deployed this change as part of `3.3.3`.  It also includes a fix for using filter functions on nested properties as well, such that:
```js
 buildQuery({ filter: { Department: { Name: { contains: 'foo'} } } });
```
produces:
```
?$filter=contains(Department/Name,'foo')
```

**Comment by solidflows** [comment]
Yeah, my backend team mentioned they updated to Odata 4.3 which imposes stricter checks.

That's awesome! I saw this library and it'll help with a query form I'm building that creates an Odata URL to send to our backend service. I'm porting this to a react app so I'll be leveraging your other library as well.

I just tried the filter function and it's working now. I'll have to play with the nested properties and see if it works on my end.

Thanks for taking care of these.

**Comment by techniq** [comment]
Glad to hear.

I was using [ODataAngularResources](https://github.com/devnixs/ODataAngularResources) when I was using Angular, but after moving over to React, I couldn't find a similar library that fulfilled my needs ( I [considered](https://github.com/devnixs/ODataAngularResources/issues/71) removing that library's dependency on Angular, but ultimately wanted a simple object model that was easy to serialize (for query strings and local storage) as well as construct.  I used to use and help maintain [js-data-sql](https://github.com/js-data/js-data-sql) and enjoyed it's query object syntax (as well as MongoDB's), and thus decided to write my own to translate to OData.

Btw, if you are not aware, I also wrote [react-odata](https://github.com/techniq/react-odata) which uses `odata-query` and provides a nice React component to interface with OData endpoints.

**Comment by techniq** [comment]
Ignore the react-odata pitch, I overlooked it in your previous comment :)

**Comment by solidflows** [comment]
Haha no worries. Does react-odata work with XML requests?

**Comment by techniq** [comment]
It uses [react-fetch-component](https://github.com/techniq/react-fetch-component) under the hood (`react-odata` is basically a thing wrapper over `react-fetch-component` and `odata-query`) and thus you can change the `as` prop from the default `json` to `text` and then parse the XML however you need.

**Comment by solidflows** [comment]
Sorry for the multiple comments but just testing out the other lib is giving me high hopes for this project! If I have any comments/issues I'll let you know on the respective page.
