### ISSUE TITLE
Enable Support for Non Type Script Projects

### ISSUE THREAD

**Issue by martypowell** [techniq/odata-query#52]
When importing this package into a basic create-react-app you will get the following error:

`Could not find dependency: 'tslib' relative to '/node_modules/odata-query/dist/commonjs/index.js'`

[Live Example](https://codesandbox.io/s/dreamy-darkness-tjxr8?file=/src/App.js).

The work around is to install `tslib` along side this package.

My recommendation would be to install `tslib` as a dependency rather than a devDependency, it seems `tslib` is [recommending](https://github.com/Microsoft/tslib#npm) that anyway.

**Comment by martypowell** [comment]
@techniq I can put in these changes if you would like, but wanted to ensure this is the approach you want to take.

**Comment by techniq** [comment]
@martypowell I typically leverage [tsdx](https://github.com/jaredpalmer/tsdx) for my projects, and it appears they have [tslib](https://github.com/jaredpalmer/tsdx/blob/master/package.json#L98) as a `dependency`.  We could look at using `tsdx` and reduce our own configuration, but at the least, I think switching it to a `dependency` from `devDependency` makes since.

**Comment by martypowell** [comment]
@techniq #53 opened. If you would like any help setting up some [Github actions](https://www.npmjs.com/package/tslib) instead of using travis ci, please let me know.

**Comment by techniq** [comment]
Pushed as `6.0.1`.  Thanks again.

If you'd want to setup Github actions, I'm all for it.  I use Azure DevOps for my private projects and haven't gotten into Github actions myself, but don't mind moving from Travis CI.

**Comment by martypowell** [comment]
@techniq sounds good, I’ll add an issue and give it a whirl.

**Comment by martypowell** [comment]
@techniq confirmed this issue is resolved, you can see it in action here, https://codesandbox.io/s/dreamy-darkness-tjxr8

**Comment by techniq** [comment]
@martypowell I see that as well - https://codesandbox.io/s/108k51nzm3.  Thanks
