### ISSUE TITLE
Query size limits

### ISSUE THREAD

**Issue by ogkarademirciDH** [techniq/odata-query#59]
If my query is bigger than 50 KB, does it still work? :) (please assume server-side has no limits)

**Comment by techniq** [comment]
@ogkarademirciDH I don't know of any limits except possibly with a [query string](https://stackoverflow.com/questions/812925/what-is-the-maximum-possible-length-of-a-query-string#:~:text=Although%20officially%20there%20is%20no,a%20max%20of%202048%20characters.) length.
