### ISSUE TITLE
Parse query-string back into queryOptions-object

### ISSUE THREAD

**Issue by sebastian-ludwig** [techniq/odata-query#82]
I was wondering if there is a way to parse the query string and "recreate" the `queryOptions`.
Could be useful to receive the query in a node Mocking-Server and return some values based on a given filter for example, like this:

```
// frontend
const query = buildQuery(queryOptions);

// backend
const queryOptions = parseBackIntoObjectSomehow(query)
```

**Comment by techniq** [comment]
@sebastian-ludwig Sorry there is not and it would take a pretty good size effort to handle the full spec.  I see quite a few parsers on npm to parse an an AST, which would probably be the best start.

https://www.npmjs.com/search?q=odata+parse

**Comment by sebastian-ludwig** [comment]
@techniq You're right, I already did some investigations for other solution, but I guess there will always be some differences to your "base" `queryOptions` (which structure I really like). 
But I see, that this will require a ton of work, so I'll close this, thank you!
