### ISSUE TITLE
Add raw's description in documentation

### ISSUE THREAD

**Issue by iKrishnaSahu** [techniq/odata-query#86]
I found raw usage in one of the PR - https://github.com/techniq/odata-query/pull/9

{ SomeProp: { type: 'raw', value: `datetime'${date.toISOString()}'` }

Can you please add it's details in the documentation?

**Comment by techniq** [comment]
I took a [quick stab](https://github.com/techniq/odata-query/commit/f3c6cef08e882365fc708f5da6a90f31e3024575) at it.  Feel free to PR some refinement.
